# Generated by Django 5.0.4 on 2025-02-03 14:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, default='books/covers/default.jpg', null=True, upload_to='book/%Y/%m/', verbose_name='Bìa sách')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=255, verbose_name='Tác giả')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá tiền')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('cover_type', models.CharField(choices=[('H', 'Bìa cứng'), ('P', 'Bìa mềm')], default='P', max_length=1, verbose_name='Loại bìa')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày xuất bản')),
                ('description', models.TextField(blank=True, default='Đang cập nhật', verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Danh mục sách',
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Tên lớp')),
                ('max_students', models.PositiveSmallIntegerField(help_text='Số lượng học sinh tối đa từ 50-80', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(80)], verbose_name='Số lượng tối đa')),
                ('current_students', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số lượng hiện tại')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Các lớp học',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='students/avatars/default.png', null=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Ảnh đại diện')),
                ('full_name', models.CharField(db_index=True, max_length=150, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VN', unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Danh sách học sinh',
                'ordering': ['student_class', 'full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.classes', verbose_name='Lớp học'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_class', 'full_name'], name='idx_student_class_fullname'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone_number', 'email'], name='idx_phone_email'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('phone_number', ''), _negated=True), name='phone_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('email', ''), _negated=True), name='email_not_empty'),
        ),
    ]
