# Generated by Django 5.0.4 on 2025-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='book/covers/default.jpg', null=True, upload_to='book/%Y/%m/', verbose_name='Bìa sách'),
        ),
    ]
