# Generated by Django 5.0.4 on 2025-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='current_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng hiện tại'),
        ),
    ]
